<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;

class tablesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Schema::disableForeignKeyConstraints();
        DB::table('reserves')->truncate();
        DB::table('reservation_datas')->truncate();
        DB::table('places')->truncate();
        Schema::enableForeignKeyConstraints();

        \DB::table('places')->insert([
                ['place_id' => 1000,
                'place_name' => 'A病院',
                'address' => '京都府京都市左京区'],
                ['place_id' => 1001,
                'place_name' => 'B病院',
                'address' => '京都府京都市左京区'],
                ['place_id' => 1002,
                'place_name' => 'Cクリニック',
                'address' => '京都府京都市伏見区'],
            ]);

        \DB::table('reservation_datas')->insert([
                //A
            ['reservation_data_id' => 100,
                'place_id' => 1000,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 101,
                'place_id' => 1000,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 102,
                'place_id' => 1000,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 103,
                'place_id' => 1000,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 104,
                'place_id' => 1000,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 105,
                'place_id' => 1000,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 106,
                'place_id' => 1000,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 107,
                'place_id' => 1000,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 108,
                'place_id' => 1000,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 109,
                'place_id' => 1000,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 110,
                'place_id' => 1000,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 111,
                'place_id' => 1000,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 112,
                'place_id' => 1000,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 5,
            ],
            ['reservation_data_id' => 114,
                'place_id' => 1000,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 16,
            ],
            ['reservation_data_id' => 115,
                'place_id' => 1000,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 116,
                'place_id' => 1000,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 3,
            ],
            ['reservation_data_id' => 117,
                'place_id' => 1000,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 14,
            ],
            ['reservation_data_id' => 118,
                'place_id' => 1000,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 119,
                'place_id' => 1000,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 120,
                'place_id' => 1000,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            //4
            ['reservation_data_id' => 121,
                'place_id' => 1000,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 122,
                'place_id' => 1000,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 123,
                'place_id' => 1000,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 124,
                'place_id' => 1000,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 125,
                'place_id' => 1000,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 126,
                'place_id' => 1000,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 127,
                'place_id' => 1000,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 128,
                'place_id' => 1000,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 129,
                'place_id' => 1000,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 130,
                'place_id' => 1000,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 131,
                'place_id' => 1000,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 132,
                'place_id' => 1000,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 133,
                'place_id' => 1000,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 5,
            ],
            ['reservation_data_id' => 134,
                'place_id' => 1000,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 16,
            ],
            ['reservation_data_id' => 135,
                'place_id' => 1000,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 136,
                'place_id' => 1000,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 3,
            ],
            ['reservation_data_id' => 137,
                'place_id' => 1000,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 14,
            ],
            ['reservation_data_id' => 138,
                'place_id' => 1000,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 139,
                'place_id' => 1000,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 140,
                'place_id' => 1000,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '18:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            
            //B
            ['reservation_data_id' => 141,
                'place_id' => 1001,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 142,
                'place_id' => 1001,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 143,
                'place_id' => 1001,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 144,
                'place_id' => 1001,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 8,
            ],
            ['reservation_data_id' => 145,
                'place_id' => 1001,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 14,
            ],
            ['reservation_data_id' => 146,
                'place_id' => 1001,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 147,
                'place_id' => 1001,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 7,
            ],
            ['reservation_data_id' => 148,
                'place_id' => 1001,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 10,
            ],
            ['reservation_data_id' => 149,
                'place_id' => 1001,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 150,
                'place_id' => 1001,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 151,
                'place_id' => 1001,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 152,
                'place_id' => 1001,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            //4
            ['reservation_data_id' => 153,
                'place_id' => 1001,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 154,
                'place_id' => 1001,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 155,
                'place_id' => 1001,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 156,
                'place_id' => 1001,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 8,
            ],
            ['reservation_data_id' => 157,
                'place_id' => 1001,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 14,
            ],
            ['reservation_data_id' => 158,
                'place_id' => 1001,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 159,
                'place_id' => 1001,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 7,
            ],
            ['reservation_data_id' => 160,
                'place_id' => 1001,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 10,
            ],
            ['reservation_data_id' => 161,
                'place_id' => 1001,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 162,
                'place_id' => 1001,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 163,
                'place_id' => 1001,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 164,
                'place_id' => 1001,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            //C
            ['reservation_data_id' => 165,
                'place_id' => 1002,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 166,
                'place_id' => 1002,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 4,
            ],
            ['reservation_data_id' => 167,
                'place_id' => 1002,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 7,
            ],
            ['reservation_data_id' => 168,
                'place_id' => 1002,
                'reservation_date' => '2022-03-28',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 169,
                'place_id' => 1002,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 170,
                'place_id' => 1002,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 171,
                'place_id' => 1002,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 172,
                'place_id' => 1002,
                'reservation_date' => '2022-03-29',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 173,
                'place_id' => 1002,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 174,
                'place_id' => 1002,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 16,
            ],
            ['reservation_data_id' => 175,
                'place_id' => 1002,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 176,
                'place_id' => 1002,
                'reservation_date' => '2022-03-30',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 12,
            ],
            ['reservation_data_id' => 177,
                'place_id' => 1002,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 178,
                'place_id' => 1002,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 179,
                'place_id' => 1002,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 180,
                'place_id' => 1002,
                'reservation_date' => '2022-03-31',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 13,
            ],
            ['reservation_data_id' => 181,
                'place_id' => 1002,
                'reservation_date' => '2022-12-07',
                'reservation_time' => '15:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            //4
            ['reservation_data_id' => 182,
                'place_id' => 1002,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 183,
                'place_id' => 1002,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 4,
            ],
            ['reservation_data_id' => 184,
                'place_id' => 1002,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 7,
            ],
            ['reservation_data_id' => 185,
                'place_id' => 1002,
                'reservation_date' => '2022-04-18',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 18,
            ],
            ['reservation_data_id' => 186,
                'place_id' => 1002,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 187,
                'place_id' => 1002,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 188,
                'place_id' => 1002,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 189,
                'place_id' => 1002,
                'reservation_date' => '2022-04-19',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 190,
                'place_id' => 1002,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 1,
            ],
            ['reservation_data_id' => 191,
                'place_id' => 1002,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 16,
            ],
            ['reservation_data_id' => 192,
                'place_id' => 1002,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 193,
                'place_id' => 1002,
                'reservation_date' => '2022-04-20',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 12,
            ],
            ['reservation_data_id' => 194,
                'place_id' => 1002,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:00',
                'capacity' => 20,
                'reserve_counts' => 17,
            ],
            ['reservation_data_id' => 195,
                'place_id' => 1002,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '16:30',
                'capacity' => 20,
                'reserve_counts' => 20,
            ],
            ['reservation_data_id' => 196,
                'place_id' => 1002,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '17:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
            ['reservation_data_id' => 197,
                'place_id' => 1002,
                'reservation_date' => '2022-04-21',
                'reservation_time' => '17:30',
                'capacity' => 20,
                'reserve_counts' => 13,
            ],
            ['reservation_data_id' => 198,
                'place_id' => 1002,
                'reservation_date' => '2022-12-28',
                'reservation_time' => '15:00',
                'capacity' => 20,
                'reserve_counts' => 2,
            ],
        ]);

        DB::table('reserves')->insert([
            ['reserve_id' => 1,
            'users_id' => 1,
            'reservation_data_id' => 100,
            'created_at' => '2022-03-15',
            ],
            ['reserve_id' => 2,
            'users_id' => 1,
            'reservation_data_id' => 121,
            'created_at' => '2022-03-15',
            ],
        ]);


        /*foreach($places as $place){
            \App\Models\place::create($place);
         }
        foreach($reservation_datas as $reservation_data){
            \App\Models\reservation_data::create($reservation_data);
        } */
        
    }
}
